name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
  assets:
    - assets/
